### ISSUE TITLE
Retrieving tissue expression score

### ISSUE THREAD

**Issue by Ni-Ar** [BgeeDB/BgeeDB_R#30]
Hi, 

your [documentation on the Bgee website](https://www.bgee.org/support/tutorial-gene-page#expression-and-reported-absence-of-expression) explains that:

>the expression scores are based on non-parametric statistics, where conditions are ranked based on the gene expression levels. These ranks are then normalized across conditions, genes, and data types, and transformed into an expression score going from 0 (= low expression) to 100 (= high expression)...

Can I retrieve those normalised expression score values for a group of genes in different species with this R package?

I couldn't find such info in the reference manual or the vignette.

Thanks a lot!

**Comment by jwollbrett** [comment]
Hi @Ni-Ar ,

Right now only processed expression values are available using the BgeeDB R package.
The download of expression calls should be added to the BgeeDB R package in the next Bioconductor release.

For your use case you could use our JSON API. Its documentation is available [here](https://www.bgee.org/doc-api/#/Access%20Data/). The webservice you are interested in is `/data/expr_calls` in the Access data section.

Do not hesitate to contact us by email if you have questions about the JSON API.

**Comment by Ni-Ar** [comment]
Thanks a lot @jwollbrett !
