### ISSUE TITLE
A less messy default download directory

### ISSUE THREAD

**Issue by dhimmel** [BgeeDB/BgeeDB_R#4]
I ran some Bgee commands from my a new terminal (which opens in my home directory). Now, I have these items in my home: `species_Bgee_13_2.tsv`, `release.tsv`, `Homo_sapiens_Bgee_13_2`. Is there a solution that doesn't clutter my home directory? Ideally, the default could be cleaner.

***

I'm a reviewer for [BgeeDB, an R package for retrieval of curated expression datasets and for gene list expression localization enrichment tests](https://doi.org/10.12688/f1000research.9973.1) at F1000Research. As part of my review, I'm going to place code related comments on GitHub, since I think that will be cleaner and more efficient.

**Comment by julien-roux** [comment]
Hi Daniel,
Thanks for your message. These files and directories are indeed saved/created by default in the R working directory when you load a new Bgee object, for example: 
`bgee.affymetrix <- Bgee$new(species="Mus_musculus", dataType="affymetrix")`

A simple way to avoid cluttering the R working directory (in your case your home directory) is to specify another directory with the `pathToData` argument. For example:
`bgee.affymetrix <- Bgee$new(species="Mus_musculus", dataType="affymetrix", pathToData="~/myAnalyses/")`.

Don't hesitate to ask us if something else is not clear.

**Comment by julien-roux** [comment]
I think I can close this issue
@dhimmel don't hesitate to reopen if the suggestion doesn't work
