### ISSUE TITLE
official BgeeDB repository

### ISSUE THREAD

**Issue by julien-roux** [BgeeDB/BgeeDB_R#6]
After discussion with Andrea, we decided that the official place for BgeeDB package development from now on will be the BgeeDB GitHub (project BgeeDB_R, https://github.com/BgeeDB/BgeeDB_R)

As suggested by the second referee of our paper (https://f1000research.com/articles/5-2748/v1#referee-response-18221), it would be a good idea to unlink the old wirawara project and the now official BgeeDB_R project.

@wirawara, could you make the BgeeDB project on your GitHub private?

**Comment by julien-roux** [comment]
I have tranferred the issues from https://github.com/wirawara/BgeeDB/issues to https://github.com/BgeeDB/BgeeDB_R/issues (and updated some of them to better reflect our current state of mind)

So to me, there is no obstacle left to render https://github.com/wirawara/BgeeDB private

@wirawara, @fbastian, @marcrr: any comment?

**Comment by marcrr** [comment]
All good for me, thanks.
